[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "server"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lightningcss"]

# Proxy rule for API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
